name: Node.js CI

on:
  push:
    branches: [ nestjs ]
  pull_request:
    branches: [ nestjs ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npx prisma generate
      - run: npm test
